config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get 'bookings/new', to: 'bookings#new'
  post 'bookings/new', to: 'bookings#create'
  resources :bookings, only: [:show]
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departure_flights, foreign_key: :departure_id, class_name: "Flight"
	has_many :arrival_flights, foreign_key: :arrival_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_many :passengers, inverse_of: :booking
	belongs_to :flight

	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :departure, class_name: "Airport"
	belongs_to :arrival, class_name: "Airport"
	has_many :bookings
	has_many :passensers, through: :bookings

	def date_formatted
		date.strftime("%m/%d/%Y")
	end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking, inverse_of: :passengers
	has_many :flights, through: :bookings
	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def new
		@flight = Flight.find_by(name: params[:flight])
		@booking = Booking.new
		params[:amount].to_i.times { @booking.passengers.build }
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save
			flash[:success] = "Flight successfully booked."
			@booking.passengers.each do |passenger|
				PassengerMailer.thank_you_email(passenger, @booking).deliver_now
			end
			redirect_to @booking
		else
			render :new
		end
	end

	def show
		@booking = Booking.find(params[:id])
	end

	private

	def booking_params
		params.require(:booking).permit(:flight_id, :amount, passengers_attributes: [:name, :email])
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

	def index
		@airports = Airport.all.map(&:code).uniq
		@dates = Flight.all.map(&:date_formatted).uniq
		unless params[:departure_id].nil?
			@flights = Flight.where(departure_id: Airport.find_by(code: params[:departure_id]).id,
									arrival_id: Airport.find_by(code: params[:arrival_id]).id)
			@flights = @flights.select { |flight| flight.date_formatted == params[:date] }
			if params[:departure_id] == params[:arrival_id]
				flash.now[:alert] = "Your departure and arrival airports cannot be the same."
			elsif @flights.empty?
				flash.now[:alert] = "No flights found matching your criteria."
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<section class="flights-form booking">
	<h3>Personal Information</h3>
			<table class="flight-info">
				<tr>
					<th>Flight No</th>
					<th>Departure</th>
					<th>Arrival</th>
					<th>Date</th>
					<th>Time</th>
					<th>Duration</th>
				</tr>
				 <tr>
					<td><%= @flight.name %></td>
					<td><%= @flight.departure.code %></td>
					<td><%= @flight.arrival.code %></td>
					<td><%= @flight.date.strftime("%m-%d-%Y") %></td>
					<td><%= @flight.date.strftime("%H:%M") %></td>
					<td><%= @flight.duration/60 %>h <%= @flight.duration%60 %>m</td>
				</tr>
			</table>
			<%= form_for(@booking, url: bookings_new_path) do |f| %>
				<%= f.text_field(:flight_id, type: "hidden", value: @flight.id) %>
				<%= f.text_field(:amount, type: "hidden", value: params[:amount]) %>
				<div class="user">
					<%= f.fields_for(:passengers) do |form| %>
						<div class="passenger">
							<h3>Passenger</h3>
							<%= form.label(:name, class: "label label-name") %>
							<%= form.text_field(:name, class: "input name", required: true) %>
							<%= form.label(:email, class: "label label-name") %>
							<%= form.email_field(:email, class: "input email", required: true) %>
						</div>
					<% end %>
				<%= f.submit "Book", class: "flights-submit user-submit" %>
				</div>
			<% end %>
</section>

app/views/bookings/show.html.erb
<section class="flights-form booking show">
	<div class="flight-details">
		<h2>- Flight Details -</h2>
		<table class="flight-info">
			<tr>
				<th>Flight No</th>
				<th>Departure</th>
				<th>Arrival</th>
				<th>Date</th>
				<th>Time</th>
				<th>Duration</th>
			</tr>
			 <tr>
				<td><%= @booking.flight.name %></td>
				<td><%= @booking.flight.departure.code %></td>
				<td><%= @booking.flight.arrival.code %></td>
				<td><%= @booking.flight.date.strftime("%m-%d-%Y") %></td>
				<td><%= @booking.flight.date.strftime("%H:%M") %></td>
				<td><%= @booking.flight.duration/60 %>h <%= @booking.flight.duration%60 %>m</td>
			</tr>
		</table>
	</div>
	<div class="personal-details">
		<h2>- Personal Details -</h2>
		<table class="flight-info">
			<tr>
				<th>Name</th>
				<th>Email</th>
			</tr>
			<% @booking.passengers.each do |passenger| %>
				 <tr>
					<td><%= passenger.name %></td>
					<td><%= passenger.email %></td>
				</tr>
			<% end %>
		</table>
	</div>
</section>

app/views/flights/_flights_pick_form.html.erb
<section class="flights">
	<h3>Pick your flight</h3>
	<table>
		<tr>
			<th class="empty"></th>
			<th>Flight No</th>
			<th>Departure</th>
			<th>Arrival</th>
			<th>Date</th>
			<th>Time</th>
			<th>Duration</th>
		</tr>
		<%= form_tag({controller: "bookings", action: "new"}, method: "get") do |f| %>
			<% @flights.each do |flight| %>
				 <tr>
					<td><%= radio_button_tag(:flight, flight.name, :checked) %></td>
					<td><%= flight.name %></td>
					<td><%= flight.departure.code %></td>
					<td><%= flight.arrival.code %></td>
					<td><%= flight.date.strftime("%m-%d-%Y") %></td>
					<td><%= flight.date.strftime("%H:%M") %></td>
					<td><%= flight.duration/60 %>h <%= flight.duration%60 %>m</td>
				</tr>
			<% end %>
			</table>
			<%= hidden_field_tag(:amount, params[:amount]) %>
			<%= submit_tag "Submit", class: "flights-submit" %>
		<% end %>
</section>

app/views/flights/index.html.erb
<section class="flights-form">
	<h3>Choose your destination</h3>
	<%= form_tag({controller: "flights", action: "index" }, method: "get") do %>
		<div class="first">
			<div class="from">
				<%= label_tag :departure_id, "From:", class: "label" %>
				<%= select_tag(:departure_id, options_for_select(@airports), class: "input") %>
			</div>
			<div class="to">
				<%= label_tag :arrival_id, "To:", class: "label" %>
				<%= select_tag(:arrival_id, options_for_select(@airports), class: "input" ) %>
			</div>
		</div>
		<div class="second">
			<div class="date">
				<%= label_tag :date, "Date:", class: "label" %>
				<%= select_tag(:date, options_for_select(@dates), class: "input") %>
			</div>
			<div class="amount">
				<%= label_tag :amount, "Passengers:", class: "label" %>
				<%= select_tag(:amount, options_for_select([1,2,3,4]), class: "input") %>
			</div>
		</div>
		<div class="submit">
			<%= submit_tag "Search", class: "form-submit" %>
		</div>
	<% end %>
</section>

<% if @flights && !@flights.empty? %>
	<%= render "flights_pick_form" %>
<% end %>

app/views/layouts/_alert.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= key %>">
        <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Odin Booker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'reset' %>
    <%= stylesheet_link_tag	   'main' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 	<header>
	  	<h1><%= link_to "The Odin Booker", root_url %></h1>
	</header>

	<% unless flash.empty? %>
		<%= render "layouts/alert" %>
	<% end %>

	<%= yield %>

	<footer>
	    <small>by S.Q.</small>
	</footer>
  </body>
</html>